IF EXISTS ( SELECT  *
            FROM    sys.objects
            WHERE   object_id = OBJECT_ID(N'udf_patientset_sql')
                    AND type IN ( N'FN', N'IF', N'TF', N'FS' ) )
DROP FUNCTION udf_patientset_sql
;

CREATE FUNCTION [dbo].[udf_patientset_sql](
	@RESULT_INSTANCE_ID INT = NULL,
	@MIN_ROW INT = NULL,
	@MAX_ROW INT = NULL,
	@TABLE_INSTANCE_ID INT = NULL
)
RETURNS NVARCHAR(MAX)
BEGIN



	DECLARE @patientset_sql NVARCHAR(MAX) = ''

	IF @RESULT_INSTANCE_ID IS NULL
		SELECT @patientset_sql = 'SELECT PATIENT_NUM FROM (SELECT PATIENT_NUM, ROW_NUMBER() OVER (ORDER BY PATIENT_NUM) SET_INDEX from PATIENT_DIMENSION) x WHERE 1=1'

	IF @RESULT_INSTANCE_ID IS NOT NULL AND @RESULT_INSTANCE_ID > 0
		SELECT @patientset_sql = 'SELECT PATIENT_NUM FROM QT_PATIENT_SET_COLLECTION where RESULT_INSTANCE_ID = ' + CAST(@RESULT_INSTANCE_ID AS NVARCHAR(20))


	IF @RESULT_INSTANCE_ID = -1
	BEGIN

	--	DECLARE @TABLE_INSTANCE_ID INT = 139, @patientset_sql NVARCHAR(4000)

	DECLARE
		@C_TABLENAME VARCHAR(50),
		@CONSTRAIN_BY_DATE_TO Varchar(100),
		@CONSTRAIN_BY_DATE_FROM Varchar(100),
		@CONSTRAIN_BY_VALUE_OPERATOR VARCHAR(20),
		@CONSTRAIN_BY_VALUE_CONSTRAINT VARCHAR(1000),
		@CONSTRAIN_BY_VALUE_UNIT_OF_MEASURE VARCHAR(50),
		@CONSTRAIN_BY_VALUE_TYPE VARCHAR(50),
		@C_COLUMNNAME VARCHAR(30),
		@C_COLUMNDATATYPE VARCHAR(50),
		@C_DIMCODE VARCHAR(1000),
		@C_OPERATOR VARCHAR(30),
		@C_FACTTABLECOLUMN VARCHAR(100)

	DECLARE
		@constraint_sql NVARCHAR(MAX),
		@ontology_constraint_sql NVARCHAR(MAX)

	DECLARE
		@COHORT_COL_INDEX INT,
		@MAX_COHORT_COL_INDEX INT,
		@current_patientset_sql NVARCHAR(MAX)


		DECLARE @cohort_col TABLE ( [C_FACTTABLECOLUMN] varchar(50),
									[C_TABLENAME] varchar(100),
									[C_COLUMNNAME] varchar(30),
									[C_COLUMNDATATYPE] varchar(50),
									[C_OPERATOR] varchar(30),
									[C_DIMCODE] varchar(1000),
									[CONSTRAIN_BY_DATE_TO] datetime,
									[CONSTRAIN_BY_DATE_FROM] datetime,
									[CONSTRAIN_BY_VALUE_OPERATOR] varchar(20),
									[CONSTRAIN_BY_VALUE_CONSTRAINT] varchar(1000),
									[CONSTRAIN_BY_VALUE_UNIT_OF_MEASURE] varchar(50),
									[CONSTRAIN_BY_VALUE_TYPE] varchar(50),
									[COHORT_INDEX] INT)

		INSERT @cohort_col
		SELECT [C_FACTTABLECOLUMN], [C_TABLENAME], [C_COLUMNNAME], [C_COLUMNDATATYPE], [C_OPERATOR], [C_DIMCODE],
				[CONSTRAIN_BY_DATE_TO], [CONSTRAIN_BY_DATE_FROM], [CONSTRAIN_BY_VALUE_OPERATOR], [CONSTRAIN_BY_VALUE_CONSTRAINT],
				[CONSTRAIN_BY_VALUE_UNIT_OF_MEASURE], [CONSTRAIN_BY_VALUE_TYPE],
				ROW_NUMBER() OVER (ORDER BY SET_INDEX) COHORT_INDEX
		from RPDO_TABLE_REQUEST where USE_AS_COHORT = 'Y' AND DELETE_FLAG = 'N' AND C_VISUALATTRIBUTES LIKE '_A%'  AND TABLE_INSTANCE_ID = @TABLE_INSTANCE_ID

		SELECT	@COHORT_COL_INDEX=1,
				@MAX_COHORT_COL_INDEX=(SELECT MAX(COHORT_INDEX) FROM @cohort_col)

		WHILE @COHORT_COL_INDEX <= @MAX_COHORT_COL_INDEX
		BEGIN

			SELECT
				@C_TABLENAME = C_TABLENAME,
				@CONSTRAIN_BY_DATE_TO =  CONSTRAIN_BY_DATE_TO,
				@CONSTRAIN_BY_DATE_FROM = CONSTRAIN_BY_DATE_FROM,
				@CONSTRAIN_BY_VALUE_OPERATOR = CONSTRAIN_BY_VALUE_OPERATOR,
				@CONSTRAIN_BY_VALUE_CONSTRAINT = CONSTRAIN_BY_VALUE_CONSTRAINT,
				@CONSTRAIN_BY_VALUE_UNIT_OF_MEASURE = CONSTRAIN_BY_VALUE_UNIT_OF_MEASURE,
				@CONSTRAIN_BY_VALUE_TYPE = CONSTRAIN_BY_VALUE_TYPE,
				@C_FACTTABLECOLUMN = C_FACTTABLECOLUMN,
				@C_COLUMNNAME = C_COLUMNNAME,
				@C_COLUMNDATATYPE = C_COLUMNDATATYPE,
				@C_DIMCODE = C_DIMCODE,
				@C_OPERATOR = C_OPERATOR
			FROM @cohort_col
			WHERE COHORT_INDEX = @COHORT_COL_INDEX

			-- Support multifact tables
			DECLARE @C_FACTTABLE VARCHAR(100) = 'observation_fact'
			IF @C_FACTTABLECOLUMN LIKE '%.%'
			BEGIN
				SET @C_FACTTABLE = LEFT(@C_FACTTABLECOLUMN, charindex('.', @C_FACTTABLECOLUMN)-1)
				SET @C_FACTTABLECOLUMN = replace(@C_FACTTABLECOLUMN, @C_FACTTABLE+'.', '')
			END

			EXEC @constraint_sql = dbo.udf_constraint_sql
				@C_TABLENAME = @C_TABLENAME,
				@CONSTRAIN_BY_DATE_TO = @CONSTRAIN_BY_DATE_TO ,
				@CONSTRAIN_BY_DATE_FROM = @CONSTRAIN_BY_DATE_FROM ,
				@CONSTRAIN_BY_VALUE_OPERATOR = @CONSTRAIN_BY_VALUE_OPERATOR,
				@CONSTRAIN_BY_VALUE_CONSTRAINT= @CONSTRAIN_BY_VALUE_CONSTRAINT ,
				@CONSTRAIN_BY_VALUE_UNIT_OF_MEASURE = @CONSTRAIN_BY_VALUE_UNIT_OF_MEASURE,
				@CONSTRAIN_BY_VALUE_TYPE = @CONSTRAIN_BY_VALUE_TYPE

			EXEC @ontology_constraint_sql = dbo.udf_constraint_ontology_sql
				@C_OPERATOR = @C_OPERATOR,
				@C_COLUMNNAME = @C_COLUMNNAME,
				@C_COLUMNDATATYPE = @C_COLUMNDATATYPE,
				@C_DIMCODE = @C_DIMCODE

			SELECT @current_patientset_sql =
				'select distinct patient_num from ' + @C_FACTTABLE + ' f
				 where f.' + @C_FACTTABLECOLUMN + ' IN
					(select ' + @C_FACTTABLECOLUMN + '
					 from ' + @C_TABLENAME + '
					 where ' + @ontology_constraint_sql + ') ' +
					 @constraint_sql

			IF @COHORT_COL_INDEX < @MAX_COHORT_COL_INDEX
				SELECT @patientset_sql += @current_patientset_sql + ' UNION '

			IF @COHORT_COL_INDEX = @MAX_COHORT_COL_INDEX
				SELECT @patientset_sql += @current_patientset_sql

			SELECT @COHORT_COL_INDEX = 	@COHORT_COL_INDEX+1

		END

		select @patientset_sql = 'SELECT PATIENT_NUM FROM (SELECT PATIENT_NUM, ROW_NUMBER() OVER (ORDER BY PATIENT_NUM) SET_INDEX FROM (' + @patientset_sql + ') x) x2 WHERE 1=1'

	END

	IF @MIN_ROW IS NOT NULL
		SELECT @patientset_sql += ' AND SET_INDEX BETWEEN ' + CAST(@MIN_ROW AS NVARCHAR(20)) + ' AND ' + CAST(@MAX_ROW AS NVARCHAR(20))

	RETURN @patientset_sql

END

