IF EXISTS ( SELECT  *
            FROM    sys.objects
            WHERE   object_id = OBJECT_ID(N'udf_constraint_sql')
                    AND type IN ( N'P', N'PC' ) ) 
DROP PROCEDURE udf_constraint_sql
;


CREATE FUNCTION [dbo].[udf_constraint_sql]
(
	@C_TABLENAME NVARCHAR(100),
	@CONSTRAIN_BY_DATE_FROM Varchar(100),
	@CONSTRAIN_BY_DATE_TO Varchar(100),
	@CONSTRAIN_BY_VALUE_OPERATOR VARCHAR(20),
	@CONSTRAIN_BY_VALUE_CONSTRAINT VARCHAR(1000),
	@CONSTRAIN_BY_VALUE_UNIT_OF_MEASURE VARCHAR(50),
	@CONSTRAIN_BY_VALUE_TYPE VARCHAR(50)
)
RETURNS NVARCHAR(4000)
BEGIN

--QA

--DECLARE @C_TABLENAME VARCHAR(50)= 'concept_dimension'
--DECLARE @CONSTRAIN_BY_DATE_TO Varchar(20) = '12/1/2019 12:00'
--DECLARE @CONSTRAIN_BY_DATE_FROM Varchar(20) = '12/31/2019 12:00'
--DECLARE @CONSTRAIN_BY_VALUE_OPERATOR VARCHAR(20) = 'GE'
--DECLARE @CONSTRAIN_BY_VALUE_CONSTRAINT VARCHAR(1000) = '6.5'
--DECLARE @CONSTRAIN_BY_VALUE_UNIT_OF_MEASURE VARCHAR(50) = ''
--DECLARE @CONSTRAIN_BY_VALUE_TYPE VARCHAR(50) = 'N'

DECLARE @SQLConstraint NVARCHAR(4000) = ''

--Date constraints
IF @CONSTRAIN_BY_DATE_FROM IS NOT NULL AND @CONSTRAIN_BY_DATE_FROM <> ''
	SELECT @SQLConstraint += ' AND CONVERT(DATE, START_DATE) >= CONVERT(DATE, '''+@CONSTRAIN_BY_DATE_FROM+''')'

IF @CONSTRAIN_BY_DATE_TO IS NOT NULL AND @CONSTRAIN_BY_DATE_TO <> ''
	SELECT @SQLConstraint += ' AND CONVERT(DATE, START_DATE) <=  CONVERT(DATE, '''+@CONSTRAIN_BY_DATE_TO+''')'

--SELECT @SQLConstraint

--EQ/NE/GT/GE/LT/LE/IN/BETWEEN/LIKE[exact]/LIKE[begin]/LIKE[end]/LIKE[contains]/CONTAINS[database]
--Concept_Dimension
IF @C_TABLENAME = 'concept_dimension'
	BEGIN
		--Numeric constraints
		IF @CONSTRAIN_BY_VALUE_TYPE = 'NUMBER' -- operators for number are EQ/NE/GT/GE/LT/LE/BETWEEN
		BEGIN
			IF @CONSTRAIN_BY_VALUE_OPERATOR = 'EQ' --equal
					SELECT @CONSTRAIN_BY_VALUE_OPERATOR = '='
			IF @CONSTRAIN_BY_VALUE_OPERATOR = 'NE' --not equal
					SELECT @CONSTRAIN_BY_VALUE_OPERATOR = '<>'
			IF @CONSTRAIN_BY_VALUE_OPERATOR = 'GT' --greater than
					SELECT @CONSTRAIN_BY_VALUE_OPERATOR = '>'
			IF @CONSTRAIN_BY_VALUE_OPERATOR = 'GE' --greater than or equal
					SELECT @CONSTRAIN_BY_VALUE_OPERATOR = '>='
			IF @CONSTRAIN_BY_VALUE_OPERATOR = 'LT' --less than
					SELECT @CONSTRAIN_BY_VALUE_OPERATOR = '<'
			IF @CONSTRAIN_BY_VALUE_OPERATOR = 'LE' --less than or equal
					SELECT @CONSTRAIN_BY_VALUE_OPERATOR = '<='

			SELECT @SQLConstraint += ' AND NVAL_NUM ' + @CONSTRAIN_BY_VALUE_OPERATOR + ' ' +@CONSTRAIN_BY_VALUE_CONSTRAINT
		END

		--Enum constraints
		IF @CONSTRAIN_BY_VALUE_TYPE = 'ENUM'
		BEGIN
			IF @CONSTRAIN_BY_VALUE_OPERATOR = 'LIKE' --wildcard at the beginning and end of value being constrained
				SELECT @SQLConstraint += ' AND TVAL_CHAR IN ('''+ @CONSTRAIN_BY_VALUE_CONSTRAINT + ''')'
			IF @CONSTRAIN_BY_VALUE_OPERATOR = 'IN' --wildcard at the beginning and end of value being constrained
				SELECT @SQLConstraint += ' AND TVAL_CHAR IN ' + @CONSTRAIN_BY_VALUE_CONSTRAINT
		END

		--Text constraints
		IF @CONSTRAIN_BY_VALUE_TYPE = 'TEXT'
		BEGIN
			IF @CONSTRAIN_BY_VALUE_OPERATOR = 'IN' --Multi select
				SELECT @SQLConstraint += ' AND TVAL_CHAR ' + @CONSTRAIN_BY_VALUE_OPERATOR + ' (' +@SQLConstraint + ')'

			IF @CONSTRAIN_BY_VALUE_OPERATOR = 'LIKE[exact]' --wildcard at the beginning and end of value being constrained
				SELECT @SQLConstraint += ' AND TVAL_CHAR LIKE, ''%'+@CONSTRAIN_BY_VALUE_CONSTRAINT+'%'''

			IF @CONSTRAIN_BY_VALUE_OPERATOR = 'LIKE[begin]'
				SELECT @SQLConstraint += ' AND TVAL_CHAR LIKE, ''%'+@CONSTRAIN_BY_VALUE_CONSTRAINT+''''

			IF @CONSTRAIN_BY_VALUE_OPERATOR = 'LIKE[end]'
				SELECT @SQLConstraint += ' AND TVAL_CHAR LIKE, '''+@CONSTRAIN_BY_VALUE_CONSTRAINT+'%'''

			IF @CONSTRAIN_BY_VALUE_OPERATOR = 'LIKE[contains]'
				SELECT @SQLConstraint += ' AND CONTAINS(OBSERVATION_BLOB, ''' +@CONSTRAIN_BY_VALUE_CONSTRAINT+ '''' + ')'
		END

		--Valueflag constraint
		IF @CONSTRAIN_BY_VALUE_TYPE = 'FLAG'
			SELECT @SQLConstraint += ' AND VALUEFLAG_CD ' + @CONSTRAIN_BY_VALUE_OPERATOR + ' ''' +@CONSTRAIN_BY_VALUE_CONSTRAINT+''''

		--Blob
		IF @CONSTRAIN_BY_VALUE_TYPE = 'LARGETEXT'
		BEGIN
			IF @CONSTRAIN_BY_VALUE_OPERATOR = 'CONTAINS'
				SELECT @SQLConstraint += ' AND CONTAINS(OBSERVATION_BLOB, ''' +@CONSTRAIN_BY_VALUE_CONSTRAINT+ '''' + ')'
		END

		--SELECT @SQLConstraintF1 = REPLACE(@SQLConstraint, 'F.', 'F1.') --adapted constraint for STUFF when listing all codes, names or values.
	END

RETURN @SQLConstraint

END
go

