/*
################################################################################
-- File:    usp_rpdo2.sql (MSSQL version)
-- Purpose: T‑SQL stored procedure to generate pivoted custom tables for I2B2
--          query results, returning directly in the result grid.
--
-- Invocation (SSMS / sqlcmd):
--   -- 1. Load the script:
--      :r C:\path\to\usp_rpdo2_mssql.sql
--
--   -- 2. Execute (for example):
--      EXEC dbo.usp_rpdo2
--        @TABLE_INSTANCE_ID  = 322,
--        @RESULT_INSTANCE_ID = 1333,
--        @MIN_ROW            = 1,
--        @MAX_ROW            = 10;
--      -- Results appear in the grid.
--
-- © 2025 Massachusetts General Hospital
################################################################################
*/


create PROCEDURE [dbo].[usp_rpdo2]
(
	@TABLE_INSTANCE_ID INT,
	@RESULT_INSTANCE_ID INT = NULL,
	@MIN_ROW INT = NULL,
	@MAX_ROW INT = NULL
)
AS
SET NOCOUNT ON

/*
DECLARE
	@TABLE_INSTANCE_ID INT = 322,
	@RESULT_INSTANCE_ID INT = -1,
	@MIN_ROW INT = NULL,
	@MAX_ROW INT = NULL
	*/

if object_id('tempdb..#column_definitions') is not null drop table #column_definitions

SELECT
	TABLE_INSTANCE_NAME,
	USER_ID,
	GROUP_ID,
	SET_INDEX,
	C_FACTTABLECOLUMN,
	C_TABLENAME,
	C_FULLPATH,
	C_COLUMNNAME,
	C_OPERATOR,
	C_DIMCODE,
	C_COLUMNDATATYPE,
	COLUMN_NAME,
	AGG_TYPE,
	CONVERT(VARCHAR(10),CONSTRAIN_BY_DATE_TO,121) CONSTRAIN_BY_DATE_TO,
	CONVERT(VARCHAR(10),CONSTRAIN_BY_DATE_FROM,121) CONSTRAIN_BY_DATE_FROM,
	CONSTRAIN_BY_VALUE_OPERATOR,
	CONSTRAIN_BY_VALUE_CONSTRAINT,
	CONSTRAIN_BY_VALUE_UNIT_OF_MEASURE,
	CONSTRAIN_BY_VALUE_TYPE,
	CONSTRAIN_BY_INDEXDATE_COLUMNNAME,
	CONSTRAIN_BY_INDEXDATE_FROM_DAYS,
	CONSTRAIN_BY_INDEXDATE_TO_DAYS,
	USE_AS_COHORT
INTO #column_definitions
FROM RPDO_TABLE_REQUEST
WHERE TABLE_INSTANCE_ID = @TABLE_INSTANCE_ID
AND DELETE_FLAG = 'N' AND C_VISUALATTRIBUTES LIKE '_A_' 
ORDER BY SET_INDEX


DECLARE
	@SET_INDEX INT,
	@C_TABLENAME VARCHAR(50),
	@COLUMN_NAME VARCHAR(1000),
	@C_FULLPATH VARCHAR(700),
	@AGG_TYPE VARCHAR(50),
	@CONSTRAIN_BY_DATE_TO Varchar(100),
	@CONSTRAIN_BY_DATE_FROM Varchar(100),
	@CONSTRAIN_BY_VALUE_OPERATOR VARCHAR(20),
	@CONSTRAIN_BY_VALUE_CONSTRAINT VARCHAR(1000),
	@CONSTRAIN_BY_VALUE_UNIT_OF_MEASURE VARCHAR(50),
	@CONSTRAIN_BY_VALUE_TYPE VARCHAR(50),
	@C_COLUMNNAME VARCHAR(30),
	@C_COLUMNDATATYPE VARCHAR(50),
	@C_DIMCODE VARCHAR(1000),
	@C_OPERATOR VARCHAR(30),
	@C_FACTTABLECOLUMN VARCHAR(100),
	@CONSTRAIN_BY_INDEXDATE_COLUMNNAME VARCHAR(1000),
	@CONSTRAIN_BY_INDEXDATE_FROM_DAYS INT,
	@CONSTRAIN_BY_INDEXDATE_TO_DAYS INT,
	@USE_AS_COHORT CHAR(1)


DECLARE @patientset_sql NVARCHAR(MAX) = ''

-- First construct patient set sql to pass to all columns
exec @patientset_sql = dbo.udf_patientset_sql
	@RESULT_INSTANCE_ID = @RESULT_INSTANCE_ID,
	@MIN_ROW = @MIN_ROW,
	@MAX_ROW = @MAX_ROW,
	@TABLE_INSTANCE_ID = @TABLE_INSTANCE_ID

--select @patientset_sql

DECLARE @MAX_SET_INDEX INT,
		@column_sql NVARCHAR(MAX)

SELECT @SET_INDEX=0,
		@MAX_SET_INDEX=ISNULL((SELECT MAX(SET_INDEX) FROM #column_definitions),0)



		--select * from #column_definitions



if object_id('tempdb..#results_tall') is not null drop table #results_tall

CREATE TABLE #results_tall
(
	patient_num INT,
	col VARCHAR(400),
	val VARCHAR(400)
)


WHILE @SET_INDEX <= @MAX_SET_INDEX
BEGIN


	SELECT
		@SET_INDEX = SET_INDEX,
		@C_TABLENAME = C_TABLENAME,
		@COLUMN_NAME = COLUMN_NAME,
		@C_FULLPATH = C_FULLPATH,
		@AGG_TYPE = AGG_TYPE,
		@CONSTRAIN_BY_DATE_TO =  CONSTRAIN_BY_DATE_TO,
		@CONSTRAIN_BY_DATE_FROM = CONSTRAIN_BY_DATE_FROM,
		@CONSTRAIN_BY_VALUE_OPERATOR = CONSTRAIN_BY_VALUE_OPERATOR,
		@CONSTRAIN_BY_VALUE_CONSTRAINT = CONSTRAIN_BY_VALUE_CONSTRAINT,
		@CONSTRAIN_BY_VALUE_UNIT_OF_MEASURE = CONSTRAIN_BY_VALUE_UNIT_OF_MEASURE,
		@CONSTRAIN_BY_VALUE_TYPE = CONSTRAIN_BY_VALUE_TYPE,
		@C_FACTTABLECOLUMN = C_FACTTABLECOLUMN,
		@C_COLUMNNAME = C_COLUMNNAME,
		@C_COLUMNDATATYPE = C_COLUMNDATATYPE,
		@C_DIMCODE = C_DIMCODE,
		@C_OPERATOR = C_OPERATOR,
		@CONSTRAIN_BY_INDEXDATE_COLUMNNAME = CONSTRAIN_BY_INDEXDATE_COLUMNNAME,
		@CONSTRAIN_BY_INDEXDATE_FROM_DAYS = CONSTRAIN_BY_INDEXDATE_FROM_DAYS,
		@CONSTRAIN_BY_INDEXDATE_TO_DAYS = CONSTRAIN_BY_INDEXDATE_TO_DAYS
	FROM #column_definitions
	WHERE SET_INDEX = @SET_INDEX

	exec @column_sql =
		dbo.udf_rpdo_column_sql
		@PATIENTSET_SQL = @patientset_sql,

		@COLUMN_NAME = @COLUMN_NAME,

		@C_FACTTABLECOLUMN = @C_FACTTABLECOLUMN,
		@C_TABLENAME = @C_TABLENAME,
		@C_COLUMNNAME = @C_COLUMNNAME,
		@C_COLUMNDATATYPE = @C_COLUMNDATATYPE,
		@C_DIMCODE = @C_DIMCODE,
		@C_OPERATOR = @C_OPERATOR,

		@CONSTRAIN_BY_DATE_TO  = @CONSTRAIN_BY_DATE_TO,
		@CONSTRAIN_BY_DATE_FROM = @CONSTRAIN_BY_DATE_FROM ,
		@CONSTRAIN_BY_VALUE_OPERATOR = @CONSTRAIN_BY_VALUE_OPERATOR,
		@CONSTRAIN_BY_VALUE_CONSTRAINT = @CONSTRAIN_BY_VALUE_CONSTRAINT,
		@CONSTRAIN_BY_VALUE_UNIT_OF_MEASURE = @CONSTRAIN_BY_VALUE_UNIT_OF_MEASURE,
		@CONSTRAIN_BY_VALUE_TYPE = @CONSTRAIN_BY_VALUE_TYPE,
		@AGG_TYPE = @AGG_TYPE,

		@TABLE_INSTANCE_ID = @TABLE_INSTANCE_ID,

		@CONSTRAIN_BY_INDEXDATE_COLUMNNAME = @CONSTRAIN_BY_INDEXDATE_COLUMNNAME,
		@CONSTRAIN_BY_INDEXDATE_FROM_DAYS = @CONSTRAIN_BY_INDEXDATE_FROM_DAYS,
		@CONSTRAIN_BY_INDEXDATE_TO_DAYS = @CONSTRAIN_BY_INDEXDATE_TO_DAYS

	--select @column_sql

	UPDATE RPDO_TABLE_REQUEST
	SET GENERATED_SQL = @column_sql
	WHERE TABLE_INSTANCE_ID = @TABLE_INSTANCE_ID AND SET_INDEX = @SET_INDEX

	INSERT INTO #results_tall
	exec sp_executesql @column_sql

	SELECT @SET_INDEX = @SET_INDEX+1

END


DECLARE @pivot_col NVARCHAR(MAX)
DECLARE @select_col NVARCHAR(MAX)
DECLARE @pivot_sql NVARCHAR(MAX)


-- create column selects including default NULLs for different aggregations
SELECT @select_col = COALESCE(@select_col + ', ','') +
				'ISNULL(' + QUOTENAME(left(COLUMN_NAME,128)) + ', ' +
				CASE WHEN AGG_TYPE = 'Exists' then '''No'''
					 WHEN AGG_TYPE LIKE 'Num%' then '0'
					 ELSE '''''' END + ') ' + QUOTENAME(left(COLUMN_NAME,128))
				FROM #column_definitions
				GROUP BY SET_INDEX, COLUMN_NAME, AGG_TYPE
				ORDER BY SET_INDEX

-- list of columns for PIVOT IN
SELECT @pivot_col = COALESCE(@pivot_col + ', ','') +
				 QUOTENAME(left(COLUMN_NAME,128))
				FROM #column_definitions
				GROUP BY SET_INDEX, COLUMN_NAME
				ORDER BY SET_INDEX



SET @pivot_sql='select patient_num, ' + @select_col + ' from (select patient_num,
				left(column_name, 128) col_name, val
				from (SELECT p.patient_num, co.SET_INDEX, co.column_name, co.agg_type, ce.val

					FROM ( ' + @patientset_sql + ') p
					CROSS JOIN #column_definitions co
					LEFT OUTER JOIN  #results_tall ce
						ON ce.col = co.COLUMN_NAME and p.PATIENT_NUM = ce.PATIENT_NUM) x
				) src
				PIVOT (Max(val) FOR col_name
				IN ('+@pivot_col+')) pvt'

--select @pivot_sql

exec sp_executesql @pivot_sql

