-- Table: RPDO_TABLE_REQUEST
CREATE TABLE RPDO_TABLE_REQUEST (
    TABLE_REQUEST_ID SERIAL,
    TABLE_INSTANCE_ID INTEGER NOT NULL,
    TABLE_INSTANCE_NAME VARCHAR(250) NOT NULL,
    USER_ID VARCHAR(50) NOT NULL,
    GROUP_ID VARCHAR(50) NOT NULL,
    SET_INDEX INTEGER NOT NULL,
    C_FACTTABLECOLUMN VARCHAR(50) NOT NULL,
    C_TABLENAME VARCHAR(100) NOT NULL,
    COLUMN_NAME VARCHAR(1000),
    C_FULLPATH VARCHAR(700),
    C_COLUMNNAME VARCHAR(30),
    C_COLUMNDATATYPE VARCHAR(50),
    C_OPERATOR VARCHAR(30),
    C_DIMCODE VARCHAR(1000),
    AGG_TYPE VARCHAR(50) NOT NULL,
    CONSTRAIN_BY_DATE_TO DATE,
    CONSTRAIN_BY_DATE_FROM DATE,
    CONSTRAIN_BY_VALUE_OPERATOR VARCHAR(20),
    CONSTRAIN_BY_VALUE_CONSTRAINT VARCHAR(1000),
    CONSTRAIN_BY_VALUE_UNIT_OF_MEASURE VARCHAR(50),
    CONSTRAIN_BY_VALUE_TYPE VARCHAR(50),
    CREATE_DATE DATE NOT NULL,
    DELETE_DATE DATE,
    UPDATE_DATE DATE,
    DELETE_FLAG VARCHAR(3),
    GENERATED_SQL TEXT,
    JSON_DATA TEXT,
    CONSTRAIN_BY_INDEXDATE_COLUMNNAME VARCHAR(1000),
    CONSTRAIN_BY_INDEXDATE_FROM_DAYS INTEGER,
    CONSTRAIN_BY_INDEXDATE_TO_DAYS INTEGER,
    USE_AS_COHORT CHAR(1)
);

-- Table: RPDO_LOG
CREATE TABLE RPDO_LOG (
    LOGGED TEXT
);
