CREATE GLOBAL TEMPORARY TABLE TMP_COLUMN_DEFINITIONS (
    TABLE_INSTANCE_NAME                VARCHAR2(250),
    USER_ID                            VARCHAR2(50),
    GROUP_ID                           VARCHAR2(50),
    SET_INDEX                          NUMBER,
    C_FACTTABLECOLUMN                  VARCHAR2(50),
    C_TABLENAME                        VARCHAR2(100),
    C_FULLPATH                         VARCHAR2(700),
    C_COLUMNNAME                       VARCHAR2(30),
    C_OPERATOR                         VARCHAR2(30),
    C_DIMCODE                          VARCHAR2(1000),
    C_COLUMNDATATYPE                   VARCHAR2(50),
    COLUMN_NAME                        VARCHAR2(1000),
    AGG_TYPE                           VARCHAR2(50),
    CONSTRAIN_BY_DATE_TO               DATE,
    CONSTRAIN_BY_DATE_FROM             DATE,
    CONSTRAIN_BY_VALUE_OPERATOR        VARCHAR2(20),
    CONSTRAIN_BY_VALUE_CONSTRAINT      VARCHAR2(1000),
    CONSTRAIN_BY_VALUE_UNIT_OF_MEASURE VARCHAR2(50),
    CONSTRAIN_BY_VALUE_TYPE            VARCHAR2(50),
    CONSTRAIN_BY_INDEXDATE_COLUMNNAME  VARCHAR2(1000),
    CONSTRAIN_BY_INDEXDATE_FROM_DAYS   NUMBER,
    CONSTRAIN_BY_INDEXDATE_TO_DAYS     NUMBER,
    USE_AS_COHORT                      CHAR(1)
) ON COMMIT PRESERVE ROWS;

CREATE GLOBAL TEMPORARY TABLE TMP_RESULTS_TALL (
    PATIENT_NUM NUMBER,
    COL         VARCHAR2(400),
    VAL         VARCHAR2(400)
) ON COMMIT PRESERVE ROWS;

CREATE TABLE RPDO_LOG (
    LOGGED CLOB
);

CREATE TABLE RPDO_TABLE_REQUEST (
    TABLE_REQUEST_ID                   NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TABLE_INSTANCE_ID                  NUMBER NOT NULL,
    TABLE_INSTANCE_NAME                VARCHAR2(250) NOT NULL,
    USER_ID                            VARCHAR2(50) NOT NULL,
    GROUP_ID                           VARCHAR2(50) NOT NULL,
    SET_INDEX                          NUMBER NOT NULL,
    C_FACTTABLECOLUMN                  VARCHAR2(50) NOT NULL,
    C_TABLENAME                        VARCHAR2(100) NOT NULL,
    COLUMN_NAME                        VARCHAR2(1000),
    C_FULLPATH                         VARCHAR2(700),
    C_COLUMNNAME                       VARCHAR2(30),
    C_COLUMNDATATYPE                   VARCHAR2(50),
    C_OPERATOR                         VARCHAR2(30),
    C_DIMCODE                          VARCHAR2(1000),
    AGG_TYPE                           VARCHAR2(50) NOT NULL,
    CONSTRAIN_BY_DATE_TO               DATE,
    CONSTRAIN_BY_DATE_FROM             DATE,
    CONSTRAIN_BY_VALUE_OPERATOR        VARCHAR2(20),
    CONSTRAIN_BY_VALUE_CONSTRAINT      VARCHAR2(1000),
    CONSTRAIN_BY_VALUE_UNIT_OF_MEASURE VARCHAR2(50),
    CONSTRAIN_BY_VALUE_TYPE            VARCHAR2(50),
    CREATE_DATE                        DATE,
    DELETE_DATE                        DATE,
    UPDATE_DATE                        DATE,
    DELETE_FLAG                        VARCHAR2(3),
    GENERATED_SQL                      CLOB,
    JSON_DATA                          CLOB,
    CONSTRAIN_BY_INDEXDATE_COLUMNNAME  VARCHAR2(1000),
    CONSTRAIN_BY_INDEXDATE_FROM_DAYS   NUMBER,
    CONSTRAIN_BY_INDEXDATE_TO_DAYS     NUMBER,
    USE_AS_COHORT                      CHAR(1),
    REQUIRED                           VARCHAR2(3)
);

